services:
  backend:
    build:
      context: .
    container_name: lembrago
    ports:
      - "7888:7888"
    depends_on:
      - mongodb
    networks:
      - default_network
    volumes:
      # Mapeia a pasta ./uploads (no host, relativa ao docker-compose.yml)
      # para a pasta /app/upload dentro do container 'backend'.
      - ./uploads:/app/uploads
      - ./releases:/app/releases

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: lembrago-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: jomasinas
      MONGO_INITDB_ROOT_PASSWORD: senha
    networks:
      - default_network

  redisdb:
    image: redis
    container_name: lembrago-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass senha
    networks:
      - default_network

volumes:
  mongo-data:

networks:
  default_network:
